using System;
using System.Linq;
using ExpandedLib.Definitions;
using ExpandedLib.Testing;
using Newtonsoft.Json.Linq;
using PipesAndPowerExpanded.BlockStructures.Engine.Blocks;
using Xunit;

namespace PipesAndPowerExpanded.Tests;

/// <summary>
/// Parity oracle for the flat engine sub-machine blocktypes now authored code-first (mpgenerator, fluidpump).
/// These carry no attributes, so the migration is a straight builder transcription; the shape rotations are
/// generated by <c>ShapeByTypeSpunPerOrientation</c> (derived from AngleFromSide). Goldens are the deleted JSON.
/// </summary>
public class EngineDefinitionParityTests
{
  private const string MpGenerator =
    """{"code":"enginempgenerator","class":"ppex.BlockEngineMPGenerator","entityClass":"ppex.BlockEntityEngineMpGenerator","behaviors":[{"name":"HorizontalOrientable"}],"entityBehaviors":[{"name":"ppex.BEBehaviorEngineMPGenerator"}],"blockmaterial":"Metal","variantgroups":[{"code":"side","loadFromProperties":"abstract/horizontalorientation"}],"creativeinventory":{"general":["*-north"],"ppex":["*-north"]},"shapebytype":{"*-north":{"base":"ppex:engine/mpgenerator","rotateY":0},"*-east":{"base":"ppex:engine/mpgenerator","rotateY":270},"*-south":{"base":"ppex:engine/mpgenerator","rotateY":180},"*-west":{"base":"ppex:engine/mpgenerator","rotateY":90}},"sidesolid":{"all":false},"sideopaque":{"all":false}}""";

  private const string FluidPump =
    """{"code":"enginefluidpump","class":"ppex.BlockEngineFluidPump","entityClass":"ppex.BlockEntityEngineFluidPump","behaviors":[{"name":"HorizontalOrientable"}],"entityBehaviors":[{"name":"Animatable"}],"blockmaterial":"Metal","variantgroups":[{"code":"side","loadFromProperties":"abstract/horizontalorientation"}],"creativeinventory":{"general":["*-north"],"ppex":["*-north"]},"shapebytype":{"*-north":{"base":"ppex:engine/fluidpump","rotateY":0},"*-east":{"base":"ppex:engine/fluidpump","rotateY":270},"*-south":{"base":"ppex:engine/fluidpump","rotateY":180},"*-west":{"base":"ppex:engine/fluidpump","rotateY":90}},"sidesolid":{"all":false},"sideopaque":{"all":false}}""";

  [Theory]
  [InlineData("mpgenerator")]
  [InlineData("fluidpump")]
  public void Engine_def_reproduces_the_migrated_json(string name)
  {
    (string golden, JObject actual) = name switch
    {
      "mpgenerator" => (MpGenerator, BlockEngineMPGenerator.Definitions("ppex").Single().ToJson()),
      "fluidpump" => (FluidPump, BlockEngineFluidPump.Definitions("ppex").Single().ToJson()),
      _ => throw new ArgumentOutOfRangeException(nameof(name)),
    };

    Assert.True(
      DefinitionParity.Equal(JObject.Parse(golden), actual, out string normalized),
      $"{name} engine def diverged from the migrated JSON:\n{normalized}"
    );
  }
}
