using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using ExpandedLib.Definitions;
using Newtonsoft.Json.Linq;

namespace ExpandedLib.Testing;

/// <summary>
/// Emits a mod's <c>{Mod}Blocks</c> table from its <b>code-first definitions</b>, so a layout author can
/// name a block code - with a chosen variant - without hand-writing the string.
/// <para>
/// <b>It runs the definitions rather than parsing them.</b> A Roslyn source generator would have to read
/// the fluent chains syntactically, and it would be wrong: codes reach <c>ExBlockDef.Create</c> through
/// helpers (<c>Core(domain, "puddlingfurnacecore", …)</c>, <c>Common(domain, "pipes/straight", …)</c>) and
/// <b>the helper adds variant groups the call site never shows</b>. Executing <c>Definitions(domain)</c>
/// yields the finished def, variant order and arity included, so what is emitted is what actually ships.
/// This is the goldens' own trick, and it is exact rather than approximate.
/// </para>
/// <para>
/// <b>This cannot cover vanilla codes.</b> The game declares those, so <c>VanillaCodes</c> stays
/// hand-authored - which is exactly why the historical <c>refractorygrating</c> typo was there and not in a
/// mod's own codes. Its foolproofing is a different tool.
/// </para>
/// </summary>
public static class BlockCodeEmitter
{
  /// <summary>True when <c>EXLIB_WRITE_BLOCKCODES=1</c>.
  /// <para>
  /// Deliberately <b>not</b> <c>EXLIB_WRITE_GOLDENS</c>. That flag rewrites an entire domain's goldens,
  /// which has destroyed hand-blessed work before; regenerating a code table is a different, far smaller
  /// action and must not be reachable by the same switch.
  /// </para></summary>
  public static bool WriteRequested =>
    Environment.GetEnvironmentVariable("EXLIB_WRITE_BLOCKCODES") == "1";

  /// <summary>
  /// Emits <paramref name="domain"/>'s table and compares it to the file at
  /// <paramref name="repoRelativePath"/>. Writes it instead when <see cref="WriteRequested"/>.
  /// <para>
  /// The failure message has to say how to fix it. A drift test that only reports "these differ" costs
  /// the reader a hunt for the regeneration switch every single time.
  /// </para>
  /// </summary>
  public static (bool ok, string message) CheckOrWrite(
    string domain,
    Assembly asm,
    string className,
    string namespaceName,
    string repoRelativePath
  )
  {
    string expected = Emit(domain, asm, className, namespaceName);
    string path = DefinitionGoldens.SolutionRelative(repoRelativePath);

    if (WriteRequested)
    {
      System.IO.File.WriteAllText(path, expected);
      return (true, "written");
    }

    if (!System.IO.File.Exists(path))
      return (false, $"{repoRelativePath} does not exist. Regenerate with "
        + "EXLIB_WRITE_BLOCKCODES=1 dotnet test <this project>");

    string actual = System.IO.File.ReadAllText(path).Replace("\r\n", "\n");
    if (actual == expected.Replace("\r\n", "\n"))
      return (true, "up to date");

    return (false,
      $"{repoRelativePath} is stale - the block definitions and this generated table disagree.\n"
      + "Regenerate with: EXLIB_WRITE_BLOCKCODES=1 dotnet test <this project>\n"
      + FirstDifference(actual, expected.Replace("\r\n", "\n")));
  }

  private static string FirstDifference(string actual, string expected)
  {
    string[] a = actual.Split('\n'), e = expected.Split('\n');
    for (int i = 0; i < Math.Max(a.Length, e.Length); i++)
    {
      string av = i < a.Length ? a[i] : "<end of file>";
      string ev = i < e.Length ? e[i] : "<end of file>";
      if (av != ev)
        return $"first difference at line {i + 1}:\n  on disk:    {av}\n  definitions: {ev}";
    }
    return "";
  }

  /// <summary>
  /// One emitted accessor. It carries the <b>def itself</b>, not a copy of its grammar: every code this
  /// file writes out comes from <see cref="ExBlockDef.Any"/> / <see cref="ExBlockDef.WithVariant"/>, so the
  /// generated table and the definitions cannot drift into disagreement - there is one implementation, and
  /// the emitter is merely a caller of it. This file used to recompute the wildcard rule itself, which is
  /// two copies of a decision (single-state groups are baked in, the rest wildcarded) that nothing checked.
  /// </summary>
  private sealed record Entry(string Member, string AssetPath, ExBlockDef Def)
  {
    public string Code => Def.QualifiedCode;

    public IReadOnlyList<ExVariantGroup> Groups => Def.VariantGroups;
  }

  /// <summary>
  /// The full <c>{Mod}Blocks</c> source for <paramref name="domain"/>, ready to compare against the
  /// checked-in file or write over it.
  /// </summary>
  public static string Emit(string domain, Assembly asm, string className, string namespaceName)
  {
    List<Entry> entries = Collect(domain, asm);
    var sb = new StringBuilder();

    sb.Append("// <auto-generated>\n");
    sb.Append("//   Emitted from this mod's code-first block definitions by BlockCodeEmitter.\n");
    sb.Append("//   DO NOT EDIT BY HAND - a drift test fails when this file and the definitions disagree.\n");
    sb.Append("//   To regenerate: EXLIB_WRITE_BLOCKCODES=1 dotnet test <this mod's test project>\n");
    sb.Append("// </auto-generated>\n\n");
    sb.Append($"namespace {namespaceName};\n\n");
    sb.Append("/// <summary>\n");
    sb.Append($"/// Every block <c>{domain}</c> declares, as a code you can name instead of type. Generated from\n");
    sb.Append("/// the definitions themselves, so the variant grammar here is the one that actually ships.\n");
    sb.Append("/// <para>\n");
    sb.Append("/// Vanilla codes are NOT here - the game declares those, and they stay hand-authored in\n");
    sb.Append("/// <c>VanillaCodes</c>.\n");
    sb.Append("/// </para>\n");
    sb.Append("/// </summary>\n");
    sb.Append($"public static class {className}\n{{\n");

    bool first = true;
    foreach (Entry e in entries)
    {
      if (!first)
        sb.Append('\n');
      first = false;
      AppendEntry(sb, e);
    }

    sb.Append("}\n");
    return sb.ToString();
  }

  private static void AppendEntry(StringBuilder sb, Entry e)
  {
    string groups = e.Groups.Count == 0
      ? "no variants"
      : string.Join(
        ", ",
        e.Groups.Select(g =>
          g.States.Count > 0
            ? $"{g.Name}({string.Join('|', g.States)})"
            : $"{g.Name}(from {g.FromProperties})"
        )
      );

    sb.Append($"  /// <summary><c>{e.Code}</c> - {e.AssetPath}. Variant groups: {groups}.</summary>\n");
    sb.Append($"  public static class {e.Member}\n  {{\n");
    sb.Append($"    /// <summary>The bare code, no variants: <c>{e.Code}</c>.</summary>\n");
    sb.Append($"    public const string Code = \"{e.Code}\";\n");

    // Straight off the def - the wildcard rule (single-state groups baked in, the rest wildcarded) lives
    // in ExBlockDef.Any and is not restated here.
    string any = e.Def.Any;
    if (e.Groups.Count > 0)
    {
      sb.Append($"\n    /// <summary>Any variant: <c>{any}</c>.</summary>\n");
      sb.Append($"    public const string Any = \"{any}\";\n");
    }

    foreach (ExVariantGroup g in e.Groups.Where(g => g.States.Count > 1))
    {
      sb.Append($"\n    /// <summary>The <c>{g.Name}</c> variant group.</summary>\n");
      sb.Append($"    public static class {Pascal(g.Name)}\n    {{\n");
      foreach (string state in g.States)
        sb.Append($"      public const string {Pascal(state)} = \"{state}\";\n");
      sb.Append("    }\n");
    }

    // One accessor per varying group: pin that group, wildcard the others. This is what a layout wants -
    // "a tall hopper facing north", "a straight pipe on the NS axis" - far more often than a fully
    // resolved code.
    foreach (ExVariantGroup g in e.Groups.Where(g => g.States.Count != 1))
    {
      // The interpolation hole is produced by WithVariant itself, so where the pinned segment lands is the
      // def's rule rather than a second copy of it here.
      string pattern = e.Def.WithVariant(g.Name, "{" + Ident(g.Name) + "}");
      sb.Append($"\n    /// <summary>Pin only <c>{g.Name}</c>: <c>{pattern}</c>.</summary>\n");
      sb.Append($"    public static string With{Pascal(g.Name)}(string {Ident(g.Name)}) =>\n");
      sb.Append($"      $\"{pattern}\";\n");

      // The BlockFacing overload - what a layout author actually reaches for. A legend wants "the
      // hopper on the charging face", and spelling that as a string means knowing whether this part writes
      // its facing as a word (`side`) or a letter (`orientation`) - the N4 split, which is a fact about the
      // block, not about the cell. The overload converts, so the caller states only the direction.
      // Emitted only where the states really are facings: an axis group (ns|we, nw|ne|se|sw) has no
      // BlockFacing naming one of its states, and an overload there would invite a code matching nothing.
      if (!g.IsHorizontalFacing)
        continue;

      sb.Append($"\n    /// <summary>Pin only <c>{g.Name}</c>, from a facing rather than a token: ");
      sb.Append($"<c>{pattern}</c>.</summary>\n");
      sb.Append(
        $"    public static string With{Pascal(g.Name)}(Vintagestory.API.MathTools.BlockFacing {Ident(g.Name)}) =>\n"
      );
      sb.Append(
        $"      With{Pascal(g.Name)}(ExpandedLib.Helpers.ExOrientation.TokenOf({Ident(g.Name)}, asLetter: {(g.UsesLetters ? "true" : "false")}));\n"
      );
    }

    // The fully-resolved accessor, when there is more than one thing to resolve.
    var varying = e.Groups.Where(g => g.States.Count != 1).ToList();
    if (varying.Count > 1)
    {
      string full = e.Code
        + string.Concat(
          e.Groups.Select(x => x.States.Count == 1 ? "-" + x.States[0] : "-{" + Ident(x.Name) + "}")
        );
      string args = string.Join(", ", varying.Select(g => "string " + Ident(g.Name)));
      sb.Append($"\n    /// <summary>Every group resolved: <c>{full}</c>.</summary>\n");
      sb.Append($"    public static string Of({args}) =>\n      $\"{full}\";\n");
    }

    sb.Append("  }\n");
  }

  private static List<Entry> Collect(string domain, Assembly asm)
  {
    var entries = new List<Entry>();
    var used = new HashSet<string>(StringComparer.Ordinal);

    foreach (ExBlockDef def in DefinitionGoldens.Collect(domain, asm).OfType<ExBlockDef>())
    {
      // The asset path is the unique key, not the code: several defs legitimately share one code and
      // differ by a `type` variant (`pipe` is straight, bend, tjunction, xjunction and outlet).
      string assetPath = def.Location.Path
        .Replace("blocktypes/", "")
        .Replace(".json", "");

      string member = Pascal(assetPath.Replace('/', '-'));
      // Deterministic disambiguation, so a collision never silently drops an accessor.
      string unique = member;
      for (int i = 2; !used.Add(unique); i++)
        unique = member + i.ToString(CultureInfo.InvariantCulture);

      entries.Add(new Entry(unique, assetPath, def));
    }

    // Emitted in a stable order so the file does not churn when a provider is reordered or renamed.
    entries.Sort((a, b) => string.CompareOrdinal(a.Member, b.Member));
    return entries;
  }

  /// <summary>A C# identifier from a variant-group name (<c>orientation</c> → <c>orientation</c>).</summary>
  private static string Ident(string raw)
  {
    string s = Pascal(raw);
    return char.ToLowerInvariant(s[0]) + s[1..];
  }

  /// <summary>PascalCase from a code segment: <c>pipes-straight</c> → <c>PipesStraight</c>,
  /// <c>tier1</c> → <c>Tier1</c>, <c>n</c> → <c>N</c>.</summary>
  private static string Pascal(string raw)
  {
    var sb = new StringBuilder(raw.Length);
    bool upper = true;
    foreach (char c in raw)
    {
      if (!char.IsLetterOrDigit(c))
      {
        upper = true;
        continue;
      }
      sb.Append(upper ? char.ToUpperInvariant(c) : c);
      upper = false;
    }
    // An identifier may not start with a digit; no current code does, but a metal or tier easily could.
    if (sb.Length > 0 && char.IsDigit(sb[0]))
      sb.Insert(0, '_');
    return sb.Length == 0 ? "_" : sb.ToString();
  }
}
