"""Emit test/ExpandedLib.Testing/ReleasedCodes.cs from the shipped release artifacts.

Faithfulness matters more than brevity here: the whole point of the manifest is that it is
extracted from dist/Releases rather than remembered, so this script is the derivation and is
checked in beside the output it produces.
"""

import json
import glob
import os
import itertools

REL = "dist/Releases/1.22.0"
# Vanilla's abstract/horizontalorientation - a fixed, known set.
HORIZ = ["north", "east", "south", "west"]
# Property-sourced groups whose states live in the game's assets. One representative each: a
# missing state inside a props group is a different (and far rarer) failure than a missing block,
# and the per-migration tests already pin per-variant behaviour.
PROPS_SAMPLE = {
    "horizontalorientation": HORIZ,
    "rockwithdeposit": ["granite"],
    "rock": ["granite"],
}


def group_states(g):
    if g.get("states"):
        return list(g["states"])
    props = (g.get("loadFromProperties") or "").split("/")[-1]
    return PROPS_SAMPLE.get(props, ["north"])


def collect(mod):
    out = []
    pat = os.path.join(REL, mod, "assets", mod, "blocktypes", "**", "*.json")
    for f in sorted(glob.glob(pat, recursive=True)):
        d = json.load(open(f, encoding="utf-8-sig"))
        code = d.get("code")
        if not code:
            continue
        rel = f.replace(os.sep, "/").split("blocktypes/")[-1].replace(".json", "")
        groups = [group_states(g) for g in (d.get("variantgroups") or [])]
        codes = (
            ["-".join((code,) + combo) for combo in itertools.product(*groups)]
            if groups
            else [code]
        )
        out.append((rel, code, sorted(set(codes))))
    return out


def main():
    lines = []
    a = lines.append
    a("// <auto-generated-by-derivation>")
    a("//   Extracted from dist/Releases/1.22.0 by scripts/gen-released-codes.py.")
    a("//   Hand-edit only to record a NEW release; never to make a failing test pass.")
    a("// </auto-generated-by-derivation>")
    a("")
    a("using System.Collections.Generic;")
    a("")
    a("namespace ExpandedLib.Testing;")
    a("")
    a("/// <summary>")
    a("/// Every block code that has ever <b>shipped</b>, taken from the release artifacts in")
    a("/// <c>dist/Releases/</c> rather than from memory or from the live registry.")
    a("/// <para>")
    a("/// <b>This is the migration contract.</b> A code in this list must still reach a live block")
    a("/// after migration, forever; a code that is not in it never shipped and needs no migrator at all.")
    a("/// That second half is the useful one - it is what bounds a rename wave to the ~45 paths that")
    a("/// actually escaped, instead of every block in the suite.")
    a("/// </para>")
    a("/// <para>")
    a("/// <b>Only three mods have ever shipped</b> - <c>exlib</c>, <c>ppex</c> (which became lpex, with")
    a("/// its HP half extracted to hpex and its pipe base to iwex) and <c>smex</c> (whose ironmaking half")
    a("/// became iwex). There has never been a released <c>iwex</c>, <c>lpex</c> or <c>hpex</c> build, so")
    a("/// every block added after those splits is unreleased and carries no migration debt.")
    a("/// </para>")
    a("/// <para>")
    a("/// ⓘ <c>exlib</c> 0.7.0 ships no blocktype JSON of its own - its structure filler is injected")
    a("/// code-first - but the filler <b>is</b> present in released worlds, because the shipped ppex and")
    a("/// smex multiblock layouts name it in their <c>blockNumbers</c>. It is listed here for that reason.")
    a("/// </para>")
    a("/// </summary>")
    a("public static class ReleasedCodes")
    a("{")
    a("  /// <summary>One shipped blocktype: where it lived, its base code, and every concrete code it")
    a("  /// expanded to. Property-sourced variant groups are sampled rather than enumerated (the game")
    a("  /// holds their states), so <see cref=\"Codes\"/> is representative for those, exact otherwise.</summary>")
    a("  public sealed record Shipped(string Domain, string AssetPath, string BaseCode, string[] Codes);")
    a("")

    all_entries = []
    for mod in ("ppex", "smex"):
        entries = collect(mod)
        all_entries.append((mod, entries))

    for mod, entries in all_entries:
        total = sum(len(c) for _, _, c in entries)
        a(f"  /// <summary>{mod} {'0.6.4' if mod == 'ppex' else '0.9.4'} - {len(entries)} blocktypes, {total} concrete codes.</summary>")
        a(f"  public static readonly IReadOnlyList<Shipped> {mod.capitalize()} =")
        a("  [")
        for rel, code, codes in entries:
            rendered = ", ".join(f'"{mod}:{c}"' for c in codes)
            a(f'    new("{mod}", "{rel}", "{mod}:{code}", [{rendered}]),')
        a("  ];")
        a("")

    a("  /// <summary>exlib 0.7.0 - no blocktype JSON, but the filler is written into released worlds by")
    a("  /// every mega-block footprint, so it carries the same migration contract as a placed block.</summary>")
    a('  public static readonly IReadOnlyList<Shipped> Exlib =')
    a("  [")
    a('    new("exlib", "structurefiller", "exlib:structurefiller", ["exlib:structurefiller"]),')
    a("  ];")
    a("")
    a("  /// <summary>Every shipped blocktype across all three released mods.</summary>")
    a("  public static IEnumerable<Shipped> All => [.. Ppex, .. Smex, .. Exlib];")
    a("")
    a("  /// <summary>Every concrete code that has ever been placed in a released world.</summary>")
    a("  public static IEnumerable<string> AllCodes =>")
    a("    System.Linq.Enumerable.SelectMany(All, s => s.Codes);")
    a("}")

    out = "test/ExpandedLib.Testing/ReleasedCodes.cs"
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    for mod, entries in all_entries:
        print(f"{mod}: {len(entries)} blocktypes, {sum(len(c) for _, _, c in entries)} concrete codes")
    print("wrote", out)


if __name__ == "__main__":
    main()
