using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ExpandedLib.Generators;

/// <summary>
/// Source generator that emits the static accessor class for every config POCO marked
/// <c>[ExConfigRegister(fileName, modId)]</c>. For a config <c>PpexConfig</c> it generates a
/// <c>PpexValues</c> static partial class holding the <c>ConfigFileName</c> const, the backing
/// <c>ExConfigRegister&lt;PpexConfig&gt;</c>, a <c>Load(ICoreAPI)</c> method and one read-only
/// <c>public static</c> property per config value - the boilerplate that previously had to be
/// duplicated by hand for each tunable.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ExConfigGenerator : IIncrementalGenerator
{
  private const string AttributeName =
    "ExpandedLib.Registries.Config.ExConfigRegisterAttribute";
  private const string ConfigVersionProperty = "ConfigVersion";

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    var models = context
      .SyntaxProvider.ForAttributeWithMetadataName(
        AttributeName,
        predicate: static (node, _) => node is ClassDeclarationSyntax,
        transform: static (ctx, _) => Extract(ctx)
      )
      .Where(static m => m is not null);

    context.RegisterSourceOutput(
      models,
      static (spc, model) => Emit(spc, model!)
    );
  }

  private static ConfigModel? Extract(GeneratorAttributeSyntaxContext ctx)
  {
    if (ctx.TargetSymbol is not INamedTypeSymbol type)
      return null;

    var attr = ctx.Attributes[0];
    if (attr.ConstructorArguments.Length < 2)
      return null;

    string fileName =
      attr.ConstructorArguments[0].Value as string ?? string.Empty;
    string modId = attr.ConstructorArguments[1].Value as string ?? string.Empty;

    string? accessorName =
      attr.NamedArguments.FirstOrDefault(na =>
        na.Key == "AccessorName"
      ).Value.Value as string;
    if (string.IsNullOrWhiteSpace(accessorName))
      accessorName = DefaultAccessorName(type.Name);

    bool hasMigrations = type.GetMembers("Migrations")
      .Any(m => m.IsStatic && m is IFieldSymbol or IPropertySymbol);

    var properties = type.GetMembers()
      .OfType<IPropertySymbol>()
      .Where(p =>
        !p.IsStatic
        && !p.IsIndexer
        && p.DeclaredAccessibility == Accessibility.Public
        && p.GetMethod is not null
        && p.Name != ConfigVersionProperty
      )
      .Select(p => new PropModel(
        p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
        p.Name
      ))
      .ToImmutableArray();

    string? ns = type.ContainingNamespace.IsGlobalNamespace
      ? null
      : type.ContainingNamespace.ToDisplayString();

    return new ConfigModel(
      ns,
      type.Name,
      accessorName!,
      fileName,
      modId,
      hasMigrations,
      new EquatableArray<PropModel>(properties)
    );
  }

  private static void Emit(SourceProductionContext spc, ConfigModel m)
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using Vintagestory.API.Common;");
    sb.AppendLine("using ExpandedLib.Registries.Config;");
    sb.AppendLine();
    if (m.Namespace is not null)
    {
      sb.AppendLine($"namespace {m.Namespace};");
      sb.AppendLine();
    }

    sb.AppendLine(
      "/// <summary>Generated accessor for the mod's gameplay tunables - see the"
    );
    sb.AppendLine(
      $"/// <c>{m.ConfigTypeName}</c> POCO and the <c>[ExConfig]</c> attribute on it.</summary>"
    );
    sb.AppendLine($"public static partial class {m.AccessorName}");
    sb.AppendLine("{");
    sb.AppendLine(
      "  /// <summary>Config file name, written under the game's <c>ModConfig</c> folder.</summary>"
    );
    sb.AppendLine($"  public const string ConfigFileName = \"{m.FileName}\";");
    sb.AppendLine();

    string migrationsArg = m.HasMigrations
      ? $", {m.ConfigTypeName}.Migrations"
      : string.Empty;
    sb.AppendLine(
      $"  private static readonly ExConfigRegister<{m.ConfigTypeName}> _store ="
    );
    sb.AppendLine($"    new(ConfigFileName, \"{m.ModId}\"{migrationsArg});");
    sb.AppendLine();
    sb.AppendLine(
      $"  private static {m.ConfigTypeName} _config => _store.Config;"
    );
    sb.AppendLine();
    sb.AppendLine(
      "  /// <summary>Loads the config (falling back to defaults), applies any"
    );
    sb.AppendLine(
      "  /// version-change resets and writes it back. Call once during mod startup.</summary>"
    );
    sb.AppendLine(
      "  public static void Load(ICoreAPI api) => _store.Load(api);"
    );

    foreach (var p in m.Properties.AsSpan())
    {
      sb.AppendLine();
      sb.AppendLine($"  public static {p.Type} {p.Name} => _config.{p.Name};");
    }

    sb.AppendLine("}");

    spc.AddSource(
      $"{m.AccessorName}.g.cs",
      SourceText.From(sb.ToString(), Encoding.UTF8)
    );
  }

  private static string DefaultAccessorName(string typeName) =>
    typeName.EndsWith("Config", StringComparison.Ordinal)
      ? typeName.Substring(0, typeName.Length - "Config".Length) + "Values"
      : typeName + "Values";
}

internal sealed record ConfigModel(
  string? Namespace,
  string ConfigTypeName,
  string AccessorName,
  string FileName,
  string ModId,
  bool HasMigrations,
  EquatableArray<PropModel> Properties
);

internal readonly record struct PropModel(string Type, string Name);

/// <summary>Value-equatable wrapper over <see cref="ImmutableArray{T}"/> so generator models compare
/// by content - lets the incremental pipeline cache correctly across edits.</summary>
internal readonly struct EquatableArray<T> : IEquatable<EquatableArray<T>>
  where T : IEquatable<T>
{
  private readonly ImmutableArray<T> _array;

  public EquatableArray(ImmutableArray<T> array) => _array = array;

  public ReadOnlySpan<T> AsSpan() =>
    _array.IsDefault ? ReadOnlySpan<T>.Empty : _array.AsSpan();

  public bool Equals(EquatableArray<T> other) =>
    AsSpan().SequenceEqual(other.AsSpan());

  public override bool Equals(object? obj) =>
    obj is EquatableArray<T> other && Equals(other);

  public override int GetHashCode()
  {
    unchecked
    {
      int hash = 17;
      foreach (var item in AsSpan())
        hash = hash * 31 + EqualityComparer<T>.Default.GetHashCode(item);
      return hash;
    }
  }
}
